services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped

    ports:
      - "7575:7575"

    environment:
      - TZ=Europe/Rome

    labels:
      # only for traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`home.yourdomain.com`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"

    volumes:
      - ./data:/appdata

    networks:
      - homelab
      - traefik

networks:
  homelab:
    external: true

  # only for traefik configuration
  traefik:
    external: true